dataset: "spouse"
embedding_type: "M3"
n_clusters: 8
thresholds: [0.9275, 0.9275, 0.8385, 0.9, 0.9275, 0.9275, 0.9275, 0.9275, 0.9275]
T: 1
embedding_path: "/hdd2/dyah/epoxy-clip/artifacts/OpenAI/ada/spouse_records"